---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: PRE_TASK | Install python3
      changed_when: false
      ansible.builtin.raw: |
        id_like=$(grep -Ewo "debian|fedora" /etc/os-release | uniq)
        case "${id_like}" in
          debian)
            apt update
            apt -y install python3
          ;;
          fedora)
            dnf makecache
            dnf -y install python3
          ;;
        esac

  roles:
    - role: xenion1987.user_management
      vars:
        user_management_users:
          - name: user_management_john.doe
            gecos: John Doe,Room 123,212-555-0000,212-555-3456,john.doe@world.org
            # password: 'mypassword' sha512 encrypted
            password: $6$rounds=656000$hUyQQf65j3czoiSV$I1Vk3KiUX8VyE0crWx2GeWsrBA1F8nPw.3vtuVIXcp5P5DhybLGGe20n43arYGm5ayr4zrmIgaals2KV98SZx/
            ssh_public_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDW6k6qtP1YfJ7eOSN1zDf8C6lTJuV+ethOvEJwTKJrGoQrKKukVfedjUL+e7XMszVT57iiV8rC+syZsJ6wkwJR2ahOUlU9hACbRc+X5mmVROLKlO+NaxrbMzsTJXeCJK6Oo+05f2kSPqGfjV3CZSq4Xv5mUMhaDkGUg/rqG5BIdqFDwirqxbUbPOIYeosLT1tbgxHvOTwsUqulEZS5h8mOt1Hahi1ZrfUOyharJvpc5rzYk/hq1zwTXTNtArOLCaSbvY+o61BAsnQBzg6Z+Elyrox53kWW8c0MuG0iPfehqW20eE9xZVBQfwutLmMHMNeUD2UwLDfxnoVXIlgn5T4Z4F2uMyKWKl9IsoIuguizX98SuASEXg4wsAEf2MSCxwk7AGO3yCgqRsnm7sIEEdvxUIewcuZn1ZtN0c3UjcsqRnoXgBOXpynsRStdZTPTM+o1LGma+Wp8FkMH1ZnuQ+BrCQ1ENKcS4oeTcG91Ud9Yiu/qfWVU64RrYpz0JvHWoApdzM73Xro2Sz9BuQH5uSCIya8PNEqGdH1GRDxbDkv41+scWwq/5i5CSlWmNogU377tPld9hqJJA//eniErgKO/QSJKmaDDzFe+eQh6F2Kn/NUVKqbPHbDlkYAZGT37L5iCOG1By55wwnemz40GS2Wo+a4nViDJGhuFty+4yR8fWQ== ansible-playground_20231122_194549
    - role: xenion1987.user_management
      vars:
        user_management_default_home_root: /home/converge
        user_management_users:
          - name: converge_default_home_root
    - role: xenion1987.user_management
      vars:
        user_management_default_primary_group: converge
        user_management_users:
          - name: converge_default_primary_group
