---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux9
    image: almalinux:9
    pre_build_image: true
    privileged: true
  - name: debian12
    image: debian:bookworm
    pre_build_image: true
    privileged: true
  - name: ubuntu2404
    image: ubuntu:24.04
    pre_build_image: true
    privileged: true
