---
stages:
  - test

before_script:
  - apt update && apt -y install git

ansible-lint:
  stage: test
  image: python:slim-bookworm
  script:
    - python -m pip install pre-commit
    - pre-commit run --all-files

ansible-test:
  stage: test
  image: python:slim-bookworm
  script:
    - python -m pip install 'ansible>=3.0.0'
    - sed -i "s,../../user_management,../../$CI_PROJECT_NAME," tests/test.yml
    - ansible-playbook tests/test.yml
