---
# tasks file for roles/user_management

- name: Ensure 'sudo' is installed
  ansible.builtin.package:
    name: sudo
    state: present
  when: user_management_default_sudo_mode == "sudo"

- name: "Ensure custom primary group is created"
  ansible.builtin.group:
    name: "{{ user_management_default_primary_group }}"
    state: present
  when: user_management_default_primary_group is defined and user_management_default_primary_group

- name: Ensure custom secondary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_management_default_secondary_groups }}"
  when: user_management_default_secondary_groups is defined and user_management_default_secondary_groups

- name: Ensure home directory exists
  ansible.builtin.file:
    path: "{{ user_management_default_home_root }}"
    state: directory
    mode: "0755"
  when: user_management_default_home_root is defined and user_management_default_home_root

- name: Include tasks 'manage_user'
  ansible.builtin.include_tasks:
    file: manage_user.yml
  loop: "{{ user_management_users }}"

- name: Include tasks 'manage_authorized_keys'
  ansible.builtin.include_tasks:
    file: manage_authorized_keys.yml
  loop: "{{ user_management_users }}"

- name: Include tasks 'manage_sudoers.yml' for groups
  loop: "{{ user_management_sudoers_groups }}"
  when: user_management_manage_sudoers_groups
  ansible.builtin.include_tasks:
    file: manage_sudoers.yml

- name: Include tasks 'manage_sudoers.yml' for users
  loop: "{{ user_management_sudoers_users }}"
  when: user_management_manage_sudoers_users
  ansible.builtin.include_tasks:
    file: manage_sudoers.yml
