---
- name: "GET | {{ item.name }}'s home path"
  when: item.state == "present"
  ansible.builtin.getent:
    database: passwd
    key: "{{ item.name }}"

- name: "Ensure {{ item.name }}'s '.ssh' directory exists"
  when: item.state == "present"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_facts.getent_passwd[item.name][4] }}/.ssh"
    mode: "0700"
    owner: "{{ ansible_facts.getent_passwd[item.name][1] }}"
    group: "{{ ansible_facts.getent_passwd[item.name][2] }}"

- name: "Manage authorized key(s) for {{ item.name }}"
  when:
    - item.state == "present"
    - item.ssh_public_keys is defined
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ ansible_facts.getent_passwd[item.name][4] }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ ansible_facts.getent_passwd[item.name][1] }}"
    group: "{{ ansible_facts.getent_passwd[item.name][2] }}"
