---
- name: "USER | Manage user: {{ item.name }}"
  ansible.builtin.user:
    # Use user_management_users.groups_append if defined, else append secondary groups if user_management_users.secondary_groups are defined
    append: "{{ item.groups_append if item.groups_append is defined and item.groups_append else user_management_default_secondary_groups_append | default(omit) }}"
    comment: "{{ item.gecos | default(omit) }}"
    # Use user_management_users.home_create if set, else set 'true'
    create_home: "{{ item.home_create | default(true) }}"
    # This only affects 'state=absent', it forces removal of the user and associated directories on supported platforms.
    force: "{{ item.userdel_force | default(false) }}"
    # Use user_management_users.primary_group if defined, else use user_management_users.name as primary group
    group: "{{ item.primary_group if item.primary_group is defined and item.primary_group else user_management_default_primary_group | default(omit) }}"
    # Use user_management_users.secondary_groups if defined, else skip modifying secondary groups
    groups: "{{ item.secondary_groups if item.secondary_groups is defined and item.secondary_groups else user_management_default_secondary_groups | default(omit) }}"
    # Optionally set the user's home directory.
    home: "{{ item.absolute_home_path if item.absolute_home_path is defined and item.absolute_home_path else user_management_default_home_root ~ '/' ~ item.name | default(omit) }}"
    # If set to true when used with 'home:', attempt to move the user's old home directory to the specified directory
    # if it isn't there already and the old home exists.
    move_home: "{{ item.home_move if item.home_move is defined and item.home_move else user_management_default_home_move | default(omit) }}"
    name: "{{ item.name }}"
    # This only affects 'state=absent', it attempts to remove directories associated with the user
    remove: "{{ item.userdel_remove | default(false) }}"
    # Use user_management_users.shell if defined, else use default shell as defined in defaults file
    shell: "{{ item.shell if item.shell is defined and item.shell else user_management_default_shell | default(omit) }}"
    state: "{{ item.state }}"

- name: "USER | Manage password: {{ item.name }}"
  when:
    - item.state == "present"
    - item.password is defined and item.password
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
