---
- name: "FILE | Ensure '.ssh' directory exists: {{ item.name }}"
  when: item.state | d('present') == "present"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_facts.getent_passwd[item.name][4] }}/.ssh"
    mode: "0700"
    owner: "{{ ansible_facts.getent_passwd[item.name][1] }}"
    group: "{{ ansible_facts.getent_passwd[item.name][2] }}"

- name: "TEMPLATE | Manage authorized key(s): {{ item.name }}"
  when:
    - item.state | d('present') == "present"
    - item.ssh_public_keys is defined
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: "{{ ansible_facts.getent_passwd[item.name][4] }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ ansible_facts.getent_passwd[item.name][1] }}"
    group: "{{ ansible_facts.getent_passwd[item.name][2] }}"
